apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-apps
  labels:
    app: kafka-python
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-0.kafka-broker.kafka:9092,kafka-broker-1.kafka-broker.kafka:9092,kafka-broker-2.kafka-broker.kafka:9092"
  KAFKA_TOPIC: "test-topic"
  KAFKA_GROUP_ID: "my-consumer-group"
  KAFKA_OFFSET_RESET: "earliest"
  KAFKA_NUM_MESSAGES: "10"
  KAFKA_DELAY: "1.0"
